### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by mrcodegit** [KanhaKanha123/repositories-listing#2]
Repro steps:
1. npm i
2. npm start
3. open app in browser

-  Current result

![Screenshot 2023-12-06 at 09 44 58](https://github.com/KanhaKanha123/repositories-listing/assets/49042542/29f0cfb0-cb59-468e-959c-11ab768b7647)

- Expected result
App compiles without errors

**Comment by KanhaKanha123** [comment]
This error i tried multiple times but i could not reproduce in my machine. The cause i can explain to you. When i generated new project using create-react-app. It gave the file name PascalCase, Like file name App.tsx. I prefer to use "Kebab Case" for file name and  PascalCase for component names. So just to make all app sync with same naming conventions i converted it. I just reopen the VS code and reinstall the dependencies and error never happened to me again. Sorry could not reproduce otherwise would fixed it.

**Comment by mrcodegit** [comment]
I think here is the problem

current import:
`import { App } from "./app";`

but the file is actually 'App'
<img width="353" alt="Screenshot 2023-12-11 at 12 29 40" src="https://github.com/KanhaKanha123/repositories-listing/assets/49042542/31eacbeb-17b0-4f37-a26f-ef56281d4ab7">

reinstalling deps does not help in my case, had to change the import

**Comment by KanhaKanha123** [comment]
in my codebase this file name is app.tsx. this is strange that change was not detected by git. i changed it now to app.tsx

<img width="1166" alt="Screenshot 2023-12-11 at 13 31 33" src="https://github.com/KanhaKanha123/repositories-listing/assets/49647776/df1a8926-e17a-41f2-8c60-018043e04054">
