### ISSUE TITLE
Pagination discussion

### ISSUE THREAD

**Issue by mrcodegit** [KanhaKanha123/repositories-listing#5]
"9. Pagination doesn't work properly when you jump directly from 1-4 or 1-7."

Could you please elaborate on that? what do you think is causing this? how to fix it?

**Comment by KanhaKanha123** [comment]
I fixed the pagination problem it works fine now. The problem was the way i selected the antd pagination doesn't seems to possible in this graphql api. It works well in sequence manner proper so now i used Prev and Next buttons in my custom pagination, Cursor based pagination works well with sequence. May be i am missing some knowledge here i would love to know if there is any other alternate way?

We can do with infinite scroll also. But i found better "Next and Prev" button approach, because we can go backwards too. And benefit of using this approach over infinite scroll is the Table in DOM will have always 10 rows in Next and Prev button approach. But in infinite approach table will keep on growing on scroll and DOM will be too large witch is not good in terms of performance.

**Comment by mrcodegit** [comment]
Prev/Next is fine for me. Previously you were using 'after' for both 'prev' and 'next' and pagination. New approach with before/after and start/end cursor works better
